### ISSUE TITLE
downArrow is not defined - app crash

### ISSUE THREAD

**Issue by KateFeaster** [Cinnamon-Toast-Cronch/FEC#67]
Application crashes when loading a product with more than 6 thumbnail urls with the following error message: `Uncaught ReferenceError: downArrow is not defined`. Error occurs in the <ImageThumbnail> Component.

Steps to reproduce:

1. Load the home page of the application.
2. Scroll down to the related products section
3. Click the 'Kicks YEasy 350' product

**Comment by KateFeaster** [comment]
Update: this issue can be temporarily solved by commenting out lines 71 - 85 of 'ImageThumbnails.jsx'. However a similar issue occurs on the same page where `upArrow` is not defined when a thumbnail other than the default thumbnail is clicked.

**Comment by KevZhang11** [comment]
great catch, Kate

**Comment by kallycao** [comment]
Thank you Kate! I resolved the issue by importing image files for the up and down arrow!
